version: "3.9"

services:
    db:
      image: postgres:14.7
      environment:
        POSTGRES_DB: mydb
        POSTGRES_USER: alex
        POSTGRES_PASSWORD: qwerty
        PGDATA: /postgresql/data
      ports:
        - "5432:5432"
      volumes:
        - ./pgdata:/postgresql/data
