version: "3.9"

services:
    django:
        build: ./django/
        command: "python manage.py runserver 0.0.0.0:8000"
        ports:
          - "8000:8000"
        healthcheck:
          test: [ "CMD", "curl", "--fail", "http://localhost:8000/user/profile" ]
          interval: 15s
          timeout: 25s
        restart: unless-stopped
    nginx:
        image: nginx:1.21.3
        ports:
          - "8080:8080"
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            django:
              condition: service_healthy

